version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: toug_ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=1m
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Descomente a seção abaixo se o servidor tiver placa de vídeo (NVIDIA) configurada com o Nvidia Container Toolkit.
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: toug_cloudflared
    command: tunnel --config /etc/cloudflared/config.yml run
    restart: unless-stopped
    environment:
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml
      - ./f01e1574-d27e-420e-9f8e-5091dc7d2125.json:/etc/cloudflared/f01e1574-d27e-420e-9f8e-5091dc7d2125.json
    depends_on:
      - ollama

volumes:
  ollama_data:
