version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: toug_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Descomente a seção abaixo se o servidor tiver placa de vídeo (NVIDIA) configurada com o Nvidia Container Toolkit.
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

volumes:
  ollama_data:
